import type { EventData, VenueData } from "@/lib/types"

export const eventTypes = ["concert", "livemusic", "music festival", "cultural", "theater"]

export const venuesData: VenueData[] = [
  {
    id: "venue1",
    name: "Patan Cultural Center",
    capacity: 300,
    longitude: 85.3218,
    latitude: 27.6782,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Patan Durbar Square, Lalitpur, Nepal",
  },
  {
    id: "venue2",
    name: "Pokhara Lakeside Events",
    capacity: 1000,
    longitude: 83.9679,
    latitude: 28.2104,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Lakeside, Pokhara, Nepal",
  },
  {
    id: "venue3",
    name: "Kathmandu Concert Hall",
    capacity: 500,
    longitude: 85.3157,
    latitude: 27.7172,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Sundhara, Kathmandu, Nepal",
  },
  {
    id: "venue4",
    name: "Jhamsikhel Live Stage",
    capacity: 200,
    longitude: 85.3184,
    latitude: 27.6818,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Jhamsikhel, Lalitpur, Nepal",
  },
  {
    id: "venue5",
    name: "Durbarmarg Music Lounge",
    capacity: 250,
    longitude: 85.321,
    latitude: 27.7125,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Durbarmarg, Kathmandu, Nepal",
  },
  {
    id: "venue6",
    name: "Thamel Live House",
    capacity: 400,
    longitude: 85.308,
    latitude: 27.7,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Thamel, Kathmandu, Nepal",
  },
  {
    id: "venue7",
    name: "Boudha Cultural Center",
    capacity: 600,
    longitude: 85.33,
    latitude: 27.69,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Boudha, Kathmandu, Nepal",
  },
  {
    id: "venue8",
    name: "Fewa Lakeside Amphitheater",
    capacity: 800,
    longitude: 84.0,
    latitude: 28.22,
    venueImage: "/placeholder.svg?height=200&width=400",
    address: "Near Fewa Lake, Pokhara, Nepal",
  },
]

export const eventsData: EventData[] = [
  {
    id: "event1",
    title: "Kutumba Live Performance",
    event_type: "livemusic",
    date: "2024-10-26T20:00:00.000Z",
    time: "8:00 PM",
    booked_by: "Patan Cultural Center",
    artists: ["Kutumba"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "Experience the authentic folk music of Nepal with Kutumba's live performance featuring traditional instruments and melodies that will transport you through Nepal's rich cultural heritage.",
    venue: {
      capacity: 300,
      longitude: 85.3218,
      latitude: 27.6782,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Patan Durbar Square, Lalitpur, Nepal",
    },
  },
  {
    id: "event2",
    title: "Indreni Festival",
    event_type: "music festival",
    date: "2024-11-08T14:00:00.000Z",
    time: "2:00 PM",
    booked_by: "Pokhara Lakeside Events",
    artists: ["Trishul", "The Shadows Nepal", "Albatross"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "The biggest music festival in Pokhara featuring top Nepali bands performing rock, pop, and fusion music against the backdrop of the beautiful Annapurna mountain range.",
    venue: {
      capacity: 1000,
      longitude: 83.9679,
      latitude: 28.2104,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Lakeside, Pokhara, Nepal",
    },
  },
  {
    id: "event3",
    title: "Batti Ra Chittai Concert",
    event_type: "concert",
    date: "2024-12-20T19:30:00.000Z",
    time: "7:30 PM",
    booked_by: "Kathmandu Concerts",
    artists: ["Batti Ra Chittai"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "Join us for an intimate evening with Batti Ra Chittai as they perform their hit songs and new material in this special concert event.",
    venue: {
      capacity: 500,
      longitude: 85.3157,
      latitude: 27.7172,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Sundhara, Kathmandu, Nepal",
    },
  },
  {
    id: "event4",
    title: "Night with Ciney Gurung",
    event_type: "livemusic",
    date: "2025-01-10T21:00:00.000Z",
    time: "9:00 PM",
    booked_by: "Jhamsikhel Live Stage",
    isFull: true,
    artists: ["Ciney Gurung"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "An exclusive night of soulful music with Ciney Gurung performing her greatest hits in an intimate setting. Limited seating available.",
    venue: {
      capacity: 200,
      longitude: 85.3184,
      latitude: 27.6818,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Jhamsikhel, Lalitpur, Nepal",
    },
  },
  {
    id: "event5",
    title: "1974 AD Acoustic Set",
    event_type: "livemusic",
    date: "2025-02-14T20:30:00.000Z",
    time: "8:30 PM",
    booked_by: "Durbarmarg Music Lounge",
    artists: ["1974 AD"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "A special Valentine's Day acoustic performance by legendary Nepali band 1974 AD, featuring their classic love songs in an intimate setting.",
    venue: {
      capacity: 250,
      longitude: 85.321,
      latitude: 27.7125,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Durbarmarg, Kathmandu, Nepal",
    },
  },
  {
    id: "event6",
    title: "Nepathya in Concert",
    event_type: "concert",
    date: "2025-03-21T18:00:00.000Z",
    time: "6:00 PM",
    booked_by: "Thamel Live House",
    artists: ["Nepathya"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "Experience the iconic Nepali folk-rock band Nepathya live in concert as they perform their greatest hits spanning decades of Nepali music.",
    venue: {
      capacity: 400,
      longitude: 85.308,
      latitude: 27.7,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Thamel, Kathmandu, Nepal",
    },
  },
  {
    id: "event7",
    title: "Boudha Cultural Festival",
    event_type: "cultural",
    date: "2025-04-15T16:00:00.000Z",
    time: "4:00 PM",
    booked_by: "Boudha Cultural Center",
    artists: ["Ani Choying Drolma", "Sukarma", "Kutumba"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "A celebration of Tibetan and Nepali cultural heritage featuring traditional music, dance performances, and art exhibitions around the sacred Boudhanath Stupa.",
    venue: {
      capacity: 600,
      longitude: 85.33,
      latitude: 27.69,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Boudha, Kathmandu, Nepal",
    },
  },
  {
    id: "event8",
    title: "Pokhara Music Festival",
    event_type: "music festival",
    date: "2025-05-01T15:00:00.000Z",
    time: "3:00 PM",
    booked_by: "Fewa Lakeside Amphitheater",
    artists: ["Bipul Chettri", "Bartika Eam Rai", "Night", "Phosphenes"],
    image: "/placeholder.svg?height=200&width=400",
    description:
      "A three-day music festival by the beautiful Fewa Lake featuring the best indie and mainstream artists from Nepal and beyond, with camping options available.",
    venue: {
      capacity: 800,
      longitude: 84.0,
      latitude: 28.22,
      venueImage: "/placeholder.svg?height=200&width=400",
      address: "Near Fewa Lake, Pokhara, Nepal",
    },
  },
]

